//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gencalcmfc.rc
//
#define IDADD                           3
#define IDOK_Boot                       3
#define ID_Default_Dates                3
#define UpdateCode                      3
#define SetDates                        3
#define IDDELETE                        4
#define IDOK_Add                        4
#define ID_Calculate                    4
#define DeleteCode                      4
#define CalcInterest                    4
#define IDOK_Remove                     5
#define IDTest                          5
#define IDOK_Select                     6
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GENCALTYPE                  129
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     132
#define IDD_DIALOG3                     133
#define IDD_DIALOG4                     134
#define IDD_DIALOG5                     135
#define IDD_DIALOG6                     136
#define IDD_RateCurves                  139
#define IDD_BondCalculator              146
#define IDD_CHolidayCode                151
#define IDD_FastDates                   152
#define IDD_FRNCalc                     153
#define IDC_EDIT1                       1000
#define IDC_EDIT_Term1_1                1000
#define IDC_Edit_Codedescription        1000
#define IDC_EDIT_Term2_1                1001
#define IDC_STATIC_Holiday_Code         1001
#define IDC_Edit_Code                   1001
#define IDC_EDIT_Value_Date             1002
#define IDC_EDIT_Holiday_Year           1002
#define IDC_EDIT_Clean_Price            1003
#define IDC_STATIC_Holiday_Month        1003
#define IDC_EDIT_Yield_Discount         1004
#define IDC_EDIT_Maturity_Date          1005
#define IDC_STATIC_Holiday_Year         1005
#define IDC_EDIT_Issue_Date             1006
#define IDC_STATIC_Holiday_Day          1006
#define IDC_EDIT_First_Pay_Date         1007
#define IDC_COMBO_Holiday_Month         1007
#define IDC_EDIT_Rerate_Rate1           1007
#define IDC_EDIT_Next_To_Last_Pay_Date  1008
#define IDC_COMBO_Holiday_Day           1008
#define IDC_EDIT_Rerate_Rate2           1008
#define IDC_EDIT_Rerate_Rate3           1009
#define IDC_EDIT_Service_Fee            1009
#define IDC_EDIT_Rerate_Rate4           1010
#define IDC_EDIT_Lag                    1010
#define IDC_COMBO_Type_1                1011
#define IDC_EDIT_Rerate_Rate5           1011
#define IDC_COMBO_Unit_1                1012
#define IDC_EDIT_Rerate_Rate6           1012
#define IDC_COMBO_Frequency_1           1013
#define IDC_COMBO_DayCount_1            1014
#define IDC_COMBO_EOM_1                 1015
#define IDC_COMBO_DayAdjust_1           1016
#define IDC_EDIT_Rate_1                 1017
#define IDC_LIST_Curve                  1018
#define IDC_LIST_Boot_Result            1019
#define IDC_EDIT_Start_Date             1020
#define IDC_COMBO_Source                1021
#define IDC_EDIT_End_Date               1022
#define IDC_STATIC_Instrument_Class     1024
#define IDC_COMBO_Instrument_Class      1025
#define IDC_EDIT_Interest_Rate          1026
#define IDC_STATIC_Interest_Rate        1027
#define IDC_STATIC_Value_Date           1028
#define IDC_STATIC_Previous_Coupon      1029
#define IDC_STATIC_Next_Coupon          1030
#define IDC_STATIC_Clean_Price          1031
#define IDC_STATIC_Accrued_Interest     1032
#define IDC_STATIC_Previous_Coupon_Value 1033
#define IDC_STATIC_Next_Coupon_Value    1034
#define IDC_STATIC_Accrued_Interest_Value 1035
#define IDC_STATIC_Dirty_Price          1036
#define IDC_STATIC_Dirty_Price_Value    1037
#define IDC_STATIC_Yield_Discount       1038
#define IDC_STATIC_Yield_Days           1039
#define IDC_COMBO_Yield_Days            1040
#define IDC_STATIC_Yield_Frequency      1041
#define IDC_COMBO_Yield_Frequency       1042
#define IDC_STATIC_Duration             1043
#define IDC_STATIC_Duration_Value       1044
#define IDC_STATIC_Modified_Duration    1045
#define IDC_STATIC_Modified_Duration_Value 1046
#define IDC_STATIC_Convexity            1047
#define IDC_STATIC_Convexity_Value      1048
#define IDC_STATIC_PVBP                 1049
#define IDC_STATIC_PVBP_Value           1050
#define IDC_STATIC_Maturity_Date        1051
#define IDC_STATIC_Day_Count            1052
#define IDC_STATIC_Pay_Frequency        1053
#define IDC_STATIC_Date_Format          1054
#define IDC_STATIC_Issue_Date           1055
#define IDC_STATIC_First_Pay_Date       1056
#define IDC_STATIC_Ex_Coup_Days         1057
#define IDC_STATIC_Interest_Days        1058
#define IDC_STATIC_Yield_Method         1059
#define IDC_STATIC_Calculation_Choice   1060
#define IDC_RADIO1_Yield_from_Price     1061
#define IDC_RADIO1_Price_from_Yield     1062
#define IDC_CHolidayCode                1062
#define IDC_COMBO_Day_Count             1063
#define IDC_Code                        1063
#define IDC_COMBO_Pay_Frequency         1064
#define IDC_CodeDescription             1064
#define IDC_STATIC_Ex_Coup_Days_Value   1065
#define IDC_NewCode                     1065
#define IDC_STATIC_Interest_Days_Value  1066
#define IDC_COMBO_Yield_method          1067
#define IDC_COMBO_Code                  1067
#define IDC_STATIC_EOM                  1068
#define IDC_Holidays                    1068
#define IDC_COMBO_EOM                   1069
#define IDC_Holidays_Adjust             1069
#define IDC_STATIC_Ex_Coup              1070
#define IDC_Simp_Comp                   1070
#define IDC_COMBO_Ex_Coup               1071
#define IDC_Pay_Freq                    1071
#define IDC_STATIC_Next_To_Last_Pay_Date 1072
#define IDC_Day_Count                   1072
#define IDC_COMBO_Holidays              1073
#define IDC_Rerate_Freq                 1073
#define IDC_STATIC_Holidays             1074
#define IDC_STATIC_Holiday_Adjust       1075
#define IDC_STATIC_Service_Fee          1075
#define IDC_STATIC_Simp_Comp            1076
#define IDC_STATIC_Lag                  1076
#define IDC_STATIC_Pay_Freq             1077
#define IDC_COMBO_Prepay                1077
#define IDC_STATIC_Rerate_Freq          1078
#define IDC_STATIC_Prepay               1078
#define IDC_STATIC_Rerate_Dates         1079
#define IDC_STATIC_Rerate_Rates         1080
#define IDC_STATIC_Rerate_Dates1        1081
#define IDC_STATIC_Rerate_Dates2        1082
#define IDC_STATIC_Rerate_Dates3        1083
#define IDC_STATIC_Rerate_Dates4        1084
#define IDC_STATIC_Rerate_Dates5        1085
#define IDC_STATIC_Rerate_Dates6        1086
#define IDC_STATIC_Previous_Coup        1087
#define IDC_STATIC_Next_Coup            1088
#define IDC_STATIC_Previous_Coup_Display 1089
#define IDC_STATIC_Next_Coup_Display    1090
#define IDC_STATIC_Interest_Display     1092
#define IDC_STATIC_Interest_Days_Display 1094
#define ID_BOND_CALC                    32771
#define ID_CALCULATOR_BONDS             32772
#define ID_DATES_HOLIDAYS               32773
#define ID_DATES_QUICKHOLIDAY           32774
#define ID_CALCULATOR_RATECURVES        32775
#define ID_CALCULATOR_NEWBOND           32776
#define HolidayCode                     32777
#define ID_HolidayCode                  32778
#define ID_CALCULATOR_FRNS              32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
